# Generated by Django 6.0 on 2025-12-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_forms_address_forms_city_forms_email_forms_father_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='Gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
